### ISSUE TITLE
NameError: name is not defined

### ISSUE THREAD

**Issue by d4rkd0s** [smashwilson/slack-emojinator#10]
```
(slack-emojinator) C:\Users\User\Development\slack-emojinator>python upload.py C:\Users\User\Downloads\*

Please enter the team name: testingname

Traceback (most recent call last):
  File "upload.py", line 15, in <module>
    team_name = input("Please enter the team name: ")
  File "<string>", line 1, in <module>
NameError: name 'testingname' is not defined

(slack-emojinator) C:\Users\User\Development\slack-emojinator>
```

In the above example, I am using `testingname` as my team name however anything there produces the same error.

My .env is as follows:

```
export SLACK_TEAM=testingname
export SLACK_COOKIE=a-37688960194=fBw5FWZp....HIDDEN...1823224420.1471300460
```

I have redacted the Cookie for obvious reasons... and again using testingname to not disclose our team name.

**Comment by d4rkd0s** [comment]
I am using latest Python2.x, latest PIP on Windows 10, updated.

**Comment by benoittgt** [comment]
Did you try with double quote?
```
export SLACK_TEAM="testingname"
export SLACK_COOKIE="a-37688960194=fBw5FWZp....HIDDEN...1823224420.1471300460"
```

**Comment by d4rkd0s** [comment]
Wasn't able to try that.

**Comment by d4rkd0s** [comment]
Ty @samstav for the fixes 👍 
Ty @smashwilson for closing issue 👍
